// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC0Ok-PEt9m1O5ovE4N2bKlqfKTJZfDxE',
    appId: '1:344274301648:web:8ba088cf5ba13b8e2aa4d5',
    messagingSenderId: '344274301648',
    projectId: 'lovemyshow-dd252',
    authDomain: 'lovemyshow-dd252.firebaseapp.com',
    storageBucket: 'lovemyshow-dd252.firebasestorage.app',
    measurementId: 'G-Q0PZ6TC4L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3KQCMzaV1gr1ez8qK_Ug4meuW2u0KM3c',
    appId: '1:344274301648:android:511fdb1c92bab38f2aa4d5',
    messagingSenderId: '344274301648',
    projectId: 'lovemyshow-dd252',
    storageBucket: 'lovemyshow-dd252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuSve4sU52MYNS5KcSnNaged-ao19CuAo',
    appId: '1:344274301648:ios:88d9e8144b29b9c32aa4d5',
    messagingSenderId: '344274301648',
    projectId: 'lovemyshow-dd252',
    storageBucket: 'lovemyshow-dd252.firebasestorage.app',
    iosBundleId: 'com.sagar.lovemyshow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuSve4sU52MYNS5KcSnNaged-ao19CuAo',
    appId: '1:344274301648:ios:88d9e8144b29b9c32aa4d5',
    messagingSenderId: '344274301648',
    projectId: 'lovemyshow-dd252',
    storageBucket: 'lovemyshow-dd252.firebasestorage.app',
    iosBundleId: 'com.sagar.lovemyshow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC0Ok-PEt9m1O5ovE4N2bKlqfKTJZfDxE',
    appId: '1:344274301648:web:575e13a16c84009f2aa4d5',
    messagingSenderId: '344274301648',
    projectId: 'lovemyshow-dd252',
    authDomain: 'lovemyshow-dd252.firebaseapp.com',
    storageBucket: 'lovemyshow-dd252.firebasestorage.app',
    measurementId: 'G-MDPS6LXC3X',
  );

}